'''manifolds vs pca test'''

#circle in generated by N points
N = 200

#exp var as a function of frequency dimensions
nfqs = 8
exp_var_S1 = np.zeros([nfqs])
holes = np.zeros([nfqs])
for i in range(nfqs):
    frqs = np.arange(2,1+2*(i+1),2)
    S1 = gen_mfld_period(N,fqs=frqs).T
    pca_S1  = PCA().fit(S1)
    exp_var_S1[i] = np.sum(pca_S1.explained_variance_ratio_[:3])
    S1_hom_L2 = full_hom_analysis(S1,metric='LP',order=False,R=0.1,Eps=0.1)
    S1_hom_geod = full_hom_analysis(S1,metric='geodesic',order=False,R=-1,Eps=0.01)
pca_mfld = PCA().fit_transform(S1)

plt.figure(dpi=200)
plt.plot(pca_mfld[:,0],pca_mfld[:,1],'c-o')
#plt.xlabel('PCA 1')
#plt.ylabel('PCA 2')
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
    
plt.figure(dpi=200)
plt.subplot(2,1,1)
plt.plot(pca_S1.explained_variance_ratio_,'k-o')
plt.ylim([0.096,0.104])
plt.ylabel('explained variance')
plt.xlabel('dimensions')
plt.subplot(2,1,2)
plt.plot(exp_var_S1,'k-o')
plt.ylabel('explained variance')
plt.xlabel('extra dimensions')
plt.tight_layout()

plt.figure(dpi=200)
plot_diagrams(S1_hom_L2[1],size=60)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

plt.figure(dpi=200)
plot_diagrams(S1_hom_geod[1],size=60,legend=False)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)

plt.figure(dpi=200)
plt.subplot(2,2,1)
plt.imshow(S1_hom_L2[0])
plt.axis('off')
plt.title('Euclidean')
plt.subplot(2,2,2)
plt.imshow(S1_hom_geod[0])
plt.axis('off')
plt.title('Geodesic')
plt.subplot(2,1,2)
plt.hist(np.triu(S1_hom_geod[0])[np.triu(S1_hom_geod[0])!=0],100,color='green')
plt.hist(np.triu(S1_hom_L2[0])[np.triu(S1_hom_L2[0])!=0],100,color='brown')
plt.title('Distance distributions')
plt.legend(['Geodesic distance','Euclidean distance'])
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.tight_layout()
